name: CI

on:
  push:
    branches:
      - main # Adjust this to your main branch (e.g., 'main', 'master')
  pull_request:
    branches:
      - main # Adjust this as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.18.0" # Specify the version you are using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
